---
# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  XPS 13 9300: xps.yml

arch_root: /mnt

country: United States
timezone: America/Los_Angeles
locales:
  - en_US
  - uk_UA

user:
  name: ruslan
  group: ruslan
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  - calibre
  - clang
  - evince
  - file-roller
  - gimp
  - git
  - gpick
  - hardinfo
  - keepassxc
  - neovim
  - neovim-qt
  - python-pynvim
  - ripgrep
  - tldr
  - libreoffice-still
  - digikam
  - tmux
  - tmuxp
  - mlocate
  - htop
  - httpie
  - inkscape
  - powertop
  #- gvfs  # For mounting and Trash support in Thunar
  #- thunar
  #- thunar-archive-plugin
  - man
  - bat
  - fzf
  - fd

  # Media
  - vlc
  - goldendict
  - chromium

  # Filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

  # Fonts
  - ttf-arphic-uming
  - ttf-indic-otf
# - nerd-fonts-iosevka  # package broken at the moment
  - nerd-fonts-complete

  # Spell check.
  - aspell
  - aspell-en
  - aspell-ru
  - aspell-uk
  - hunspell
  - hunspell-en_US
  - hunspell-he

extra_aur_packages:
  - github-cli
  - grimshot
  - chromium-widevine  # Google's Content Decryption Module plugin.
  - dropbox
  #  - kalu  # incompatible with latest pacman for now
  - mimeo
  - tectonic
  #- thunar-dropbox-git
  - ttf-joypixels
  - wev
  - wshowkeys

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmds:
    - "stow -d ${HOME}/dotfiles -S chromium git gnupg goldendict neovim sage alacritty tilix tmux yay zsh sway waybar"
  deps:
    - conky
    - stow
    - python-jedi
    - ctags
