---
# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  XPS 13 9300: xps.yml

arch_root: /mnt

country: United States
timezone: America/Los_Angeles
locales:
  - en_US
  - uk_UA

user:
  name: ruslan
  group: ruslan
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/zsh
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  # system
  - bat
  - fd
  - fzf
  - hardinfo
  - htop
  - man
  - mlocate
  - powertop
  - ripgrep
  - tldr
  - tmux
  - tmuxp

  # filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # archives
  - file-roller
  - p7zip
  - unrar
  - unzip
  - zip

  # developemnt
  - clang
  - git
  - httpie
  - neovim
  - neovim-qt
  - python-pynvim

  # media
  - calibre
  - chromium
  - digikam
  - evince
  - gimp
  - goldendict
  - gpick
  - inkscape
  - vlc

  # fonts
  - ttf-arphic-uming
  - ttf-indic-otf
  - nerd-fonts-complete
  #- nerd-fonts-iosevka  # package broken at the moment

  # misc
  - keepassxc
  - libreoffice-still
  #- gvfs  # For mounting and Trash support in Thunar
  #- thunar
  #- thunar-archive-plugin

  # spellcheck
  - aspell
  - aspell-en
  - aspell-ru
  - aspell-uk
  - hunspell
  - hunspell-en_US
  - hunspell-he

extra_aur_packages:
  - chromium-widevine  # Google's Content Decryption Module plugin.
  - dropbox
  - github-cli
  - mimeo
  - tectonic
  - ttf-joypixels

  #- thunar-dropbox-git
  #- kalu  # incompatible with latest pacman for now

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmds:
    - "stow -d ${HOME}/dotfiles -S sway swaylock swaynag waybar mako redshift systemd"
    - "stow -d ${HOME}/dotfiles -S yay alacritty tilix zsh tmux git gnupg neovim"
    - "stow -d ${HOME}/dotfiles -S chromium goldendict sage"
  deps:
    - conky
    - stow
    - python-jedi
    - ctags
