---
arch_root: /mnt

# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  Gazelle Professional: gzp.yml
  XPS 13 9350: xps.yml

country: United States
locales:
  - en_US
  - uk_UA

user:
  name: zoresvit
  group: zoresvit
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/bash
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  - calibre
  - clang
  - file-roller
  - gimp
  - git
  - gvfs  # For mounting and Trash support in Thunar
  - gvim
  - hardinfo
  - hasktags
  - keepassxc
  - neovim
  - python-neovim
  - ripgrep
  - thunar
  - thunar-archive-plugin
  - tldr
  - tmux
  - tmuxp

  # Media
  - smplayer
  - goldendict
  - chromium

  # Console
  - termite
  - bash-completion
  - mlocate
  - htop
  - hub
  - httpie

  # Filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

  # Fonts
  - ttf-freefont
  - ttf-arphic-uming
  - ttf-indic-otf

  # Spell check.
  - aspell
  - aspell-en
  - aspell-ru
  - aspell-uk
  - hunspell
  - hunspell-en_US
  - hunspell-he
  - muparser  # optional for Albert calculator extension

extra_aur_packages:
  - albert
  - autorandr
  - chromium-widevine  # Google's Content Decryption Module plugin.
  - dropbox
  - flameshot
  - gocode-git
  - kalu
  - mimeo
  - neovim-gtk-git
  - pasystray-gtk3-git
  - tectonic
  - thunar-dropbox-git
  - ttf-emojione
  - ttf-material-design-icons-git
  - xkb-switch
  - unclutter-xfixes-git

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S albert bash chromium conky flameshot git goldendict termite tmux vim xmonad xorg"
  deps:
    - conky
    - stow
    - xsel
    - python-jedi
    - hasktags
    - ctags
