arch_root: /mnt

# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  Gazelle Professional: gzp.yml
  XPS 13 9350: xps.yml

country: United States
locales:
  - en_US
  - uk_UA

user:
  name: zoresvit
  group: zoresvit
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/bash
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  - gvim
  - thunar
  - thunar-archive-plugin
  - keepassxc
  - git
  - tldr
  - calibre
  - ripgrep

  # Media
  - smplayer
  - goldendict
  - chromium

  # Console
  - termite
  - bash-completion
  - mlocate

  # Filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

  - muparser  # optional for Albert calculator extension

extra_aur_packages:
  - dropbox
  - albert
  - thunar-dropbox
  - ttf-material-design-icons-git
  - kalu
  - pasystray-gtk3-git
  - flameshot
  - ttf-emojione-color
  - xkb-switch
  - unclutter-xfixes-git
  - chromium-widevine  # Google's Content Decryption Module plugin.

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S albert bash chromium conky flameshot git goldendict mime termite tmux vim xmonad xorg"
  deps:
    - conky
    - stow
    - xclip
    - python-jedi
    - source-highlight
    - hasktags
    - ctags
