---
arch_root: /mnt

# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  XPS 13 9300: xps.yml

country: United States
timezone: America/Los_Angeles
locales:
  - en_US
  - uk_UA

user:
  name: ruslan
  group: ruslan
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
#    - realtime
#    - docker
  shell: /bin/zsh
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  - calibre
  - clang
  - evince
  - file-roller
  - gimp
  - git
  - gpick
  - gvfs  # For mounting and Trash support in Thunar
  - hardinfo
  - keepassxc
  - neovim
  - neovim-qt
  - python-pynvim
  - ripgrep
  - thunar
  - thunar-archive-plugin
  - tldr
  - tmux
  - tmuxp

  # Media
  - vlc
  - goldendict
  - chromium

  # Console
  - tilix
  - zsh
  - zsh-completions
  - mlocate
  - htop
  - httpie

  # Filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

  # Fonts
  - ttf-arphic-uming
  - ttf-indic-otf

  # Spell check.
  - aspell
  - aspell-en
  - aspell-ru
  - aspell-uk
  - hunspell
  - hunspell-en_US
  - hunspell-he

extra_aur_packages:
  - github-cli
  - chromium-widevine  # Google's Content Decryption Module plugin.
  - dropbox
  #  - kalu  # incompatible with latest pacman for now
  - mimeo
  - tectonic
  - thunar-dropbox-git
  - ttf-joypixels

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S albert bash zsh chromium conky flameshot git goldendict termite tmux vim xmonad xorg"
  deps:
    - conky
    - stow
    - xsel
    - python-jedi
    - hasktags
    - ctags
