---
- name: install extra packages from repo
  pacman:
    name: "{{ extra_packages }}"

- name: install host-specific packages from repo
  pacman:
    name: "{{ host_extra_packages }}"
  when: host_extra_packages | length > 0

- name: install AUR packages
  aur:
    name: "{{ extra_aur_packages }}"
  become_user: "{{ user.name }}"

- name: install ulauncher
  aur:
    name: ulauncher
  become_user: "{{ user.name }}"

- name: install host-specific packages from AUR
  aur:
    name: "{{ host_extra_aur_packages }}"
  become_user: "{{ user.name }}"
  when: host_extra_aur_packages is defined and host_extra_aur_packages|length > 0
