---
- name: install LXDM display manager
  pacman: name=lxdm state=present

- name: install dependencies
  pacman: name={{ item }} state=present
  with_items:
    - gnome-screensaver
    - xss-lock
    #- unclutter

- name: configure LXDM display manager
  copy: src=lxdm/lxdm.conf dest=/etc/lxdm/lxdm.conf backup=yes

- name: configure LXDM PostLogin hook
  copy: src=lxdm/PostLogin dest=/etc/lxdm/PostLogin

- name: enable LXDM daemon
  service: name=lxdm enabled=yes
