---

- import_tasks: xorg.yml
- import_tasks: lxdm.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: networkmanager.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman:
    name: cronie
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman:
    name:
      - compton
      - feh
      - redshift
      - trayer
      - xmobar
      - xmonad
      - xmonad-contrib
      - dunst
      - dmenu
      - deepin-screenshot
      - geeqie
      - polkit-gnome

- name: configure compton compositor
  copy:
    src: compton.conf
    dest: /etc/xdg/compton.conf
    backup: 'yes'

- name: enable redshift service
  command: systemctl --user enable redshift.service
  become_user: "{{ user.name }}"

- name: install MIME application associations
  copy:
    src: mimeapps.list
    dest: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"

- import_tasks: extra_packages.yml
