---

- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml

- name: install cron
  pacman:
    name: cronie
  notify:
    - enable cron

- name: install packages for desktop environment from repo
  pacman:
    name:
      - alacritty
      - brightnessctl
      - dmenu
      - gdm
      - geeqie
      - polkit-gnome
      - sway
      - swayidle
      - swaylock
      - wofi
      - xorg-server-xwayland
  notify:
    - enable gdm


- name: install MIME application associations
  copy:
    src: mimeapps.list
    dest: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"

- import_tasks: extra_packages.yml
