
- name: install packages for desktop environment
  pacman:
    name:
      - brightnessctl
      - dmenu
      - gdm
      - jq
      - polkit-gnome
      - sway
      - swayidle
      - swaylock
      - tilix
      - waybar
      - xorg-server-xwayland
      - wl-clipboard
      - mako
  notify:
    - enable gdm

- name: install sway-session.target
  copy:
    src: sway/sway-session.target
    dest: /etc/systemd/user/sway-session.target

- name: install waybar.service
  copy:
    src: sway/waybar.service
    dest: /etc/systemd/user/waybar.service
  notify:
    - enable waybar

- name: install swayidle.service
  copy:
    src: sway/swayidle.service
    dest: /etc/systemd/user/swayidle.service
  notify:
    - enable swayidle
