---
- name: install GTK and Qt themes
  pacman:
    name:
      - breeze
      - breeze-gtk
      - breeze-icons
      - breeze-grub
      - qt4
      - qt5-base
      - qt5ct
      - gnome-themes-extra

- name: install events sound interface
  pacman:
    name:
      - libcanberra
      - libcanberra-pulse
      - sound-theme-freedesktop

- name: install fonts
  pacman:
    name:
      - ttf-hack
      - ttf-dejavu
      - ttf-ubraille
      # Fonts to use asian characters
      - ttf-freefont
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-indic-otf
      # Emoji
      - noto-fonts
      - ttf-hannom  # Vietnamese
      # Math
      - font-mathematica

- name: configure GTK 2
  copy:
    src: gtk-2.0/gtkrc
    dest: /etc/gtk-2.0/gtkrc

- name: configure GTK 3
  copy: src=gtk-3.0/settings.ini dest=/etc/gtk-3.0/settings.ini

- name: create gtk-3.0 user config dir
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0"
    owner: "{{ user.name }}"
    state: directory

- name: create user gtk.css file for GTK 3
  copy:
    src: gtk-3.0/gtk.css
    dest: "/home/{{ user.name }}/.config/gtk-3.0/gtk.css"
    owner: "{{ user.name }}"

- name: configure Qt 4
  copy:
    src: qt/Trolltech.conf
    dest: /etc/xdg/Trolltech.conf

- name: create qt5ct config dir
  file:
    path: /home/{{ user.name }}/.config/qt5ct/
    owner: "{{ user.name }}"
    state: directory

- name: configure Qt 5
  copy:
    src: qt/qt5ct.conf
    dest: /home/{{ user.name }}/.config/qt5ct/qt5ct.conf
    owner: "{{ user.name }}"


- name: configure cursor
  lineinfile:
    path: /usr/share/icons/default/index.theme
    regexp: ^Inherits=
    line: Inherits=Breeze_Snow
