---
- name: install Xorg server
  pacman:
    name:
      - xorg
      - xterm
      - xf86-input-libinput
      - xf86-video-intel
      - arandr

- name: configure input devices
  copy: src=xorg/30-input.conf dest=/etc/X11/xorg.conf.d/30-input.conf

- name: identify video adapter vendor
  shell: "lspci | grep VGA"
  register: graphics

- name: configure video driver
  copy: src=xorg/30-video.conf dest=/etc/X11/xorg.conf.d/30-video.conf
  when: "'Intel' in graphics.stdout"

- name: add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: add user to audio group
  user: name={{ user.name }} groups=audio append=yes

- name: create dunst config dir
  file:
    path: "/etc/xdg/dunst"
    state: directory

- name: configure dunst notifications
  copy:
    src: dunstrc
    dest: "/etc/xdg/dunst/dunstrc"
