---
- name: install stow to manage symlinks
  pacman:
    name: stow

- name: check if dotfiles exist
  stat:
    path: "${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  register: dotfiles_dir

- name: clone dotfiles
  command: "git clone {{ dotfiles.repo }} ${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  when: not dotfiles_dir.stat.exists

- name: install dotfiles dependencies
  pacman:
    name: "{{ dotfiles.deps }}"

- name: install tmux plugin manager
  command: "git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm"
  become_user: "{{ user.name }}"

- name: cleanup OhMyZsh from previous installation
  file:
    path: "${HOME}/.oh-my-zsh/"
    state: absent
  become_user: "{{ user.name }}"

- name: install OhMyZsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: "{{ user.name }}"

- name: install Zsh theme powerlevel10k
  command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${HOME}/.oh-my-zsh/custom/themes/powerlevel10k"
  become_user: "{{ user.name }}"

- name: install Zsh plugin zsh-lazyload
  command: "git clone https://github.com/qoomon/zsh-lazyload ${HOME}/.oh-my-zsh/custom/plugins/zsh-lazyload"
  become_user: "{{ user.name }}"

- name: cleanup default Zsh config
  file:
    path: "${HOME}/.zshrc"
    state: absent
  become_user: "{{ user.name }}"

- name: install dotfiles
  command: "{{ item }}"
  become_user: "{{ user.name }}"
  with_items: "{{ dotfiles.install_cmds }}"

# Keepassxc config is installed here once instead of symlinked from dotfiles
# repo as keepassxc constantly rewrites its config cause changed to be added
# into Git repository.
- name: create Keepassxc config dir
  file:
    path: "${HOME}/.config/keepassxc"
    state: directory
  become_user: "{{ user.name }}"

- name: install Keepassxc config
  copy:
    src: keepassxc.ini
    dest: "${HOME}/.config/keepassxc/"
