---
- name: install stow to manage symlinks
  pacman:
    name: stow

- name: check if dotfiles exist
  stat:
    path: "${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  register: dotfiles_dir

- name: clone dotfiles
  command: "git clone {{ dotfiles.repo }} ${HOME}/dotfiles"
  become_user: "{{ user.name }}"
  when: not dotfiles_dir.stat.exists

- name: install dotfiles dependencies
  pacman:
    name: "{{ dotfiles.deps }}"

- name: cleanup OhMyZsh from previous installation
  file:
    path: "${HOME}/.oh-my-zsh"
    state: absent

- name: install dotfiles
  shell: "{{ item }}"
  become_user: "{{ user.name }}"
  with_items: "{{ dotfiles.install_cmds }}"

# Keepassxc config is installed here once instead of symlinked from dotfiles
# repo as keepassxc constantly rewrites its config cause changed to be added
# into Git repository.
- name: create Keepassxc config dir
  file:
    path: "${HOME}/.config/keepassxc"
    state: directory
  become_user: "{{ user.name }}"

- name: install Keepassxc config
  copy:
    src: keepassxc.ini
    dest: "${HOME}/.config/keepassxc/"
