---
- name: install TLP power management
  pacman: 
    name:
      - tlp
      - tlp-rdw
      - acpid
      - ethtool
      - smartmontools

- name: mask systemd radio service
  command: systemctl mask systemd-rfkill.service

- name: mask systemd radio socket
  command: systemctl mask systemd-rfkill.socket

- name: Enable TLP service
  service: name=tlp.service enabled=yes state=restarted

- name: Enable TLP sleep service
  service: name=tlp-sleep.service enabled=yes state=restarted

- name: configure systemd logind.conf
  copy: src=logind.conf dest=/etc/systemd/logind.conf
