---

- name: configure repository mirrors
  command: "reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist"

- name: upgrade system to latest state
  pacman:
    update_cache: yes
    upgrade: yes

- import_tasks: locales.yml

- name: set console font
  lineinfile:
    path: /etc/vconsole.conf
    line: "FONT=Lat2-Terminus16"
    create: yes

- name: configure hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ hostname }}"
    create: yes

- name: set hostname in /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 644

- name: install base packages
  pacman:
    name: "{{ packages }}"

- name: install intel microcode
  pacman:
    name: intel-ucode
  when: "'GenuineIntel' in ansible_processor"

- import_tasks: user.yml
- import_tasks: bootloader.yml
