---
- name: install NetworkManager and dependencies
  pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet
      - gnome-keyring

- name: configure mirrors update hook
  template:
    src: nm-mirrors-hook.sh
    dest: /etc/NetworkManager/dispatcher.d/99update-mirrors.sh
    mode: 0755

- name: enable NetworkManager
  systemd:
    name: NetworkManager.service
    enabled: yes
