---
- name: install yay AUR package helper
  aur:
    name: yay
  become_user: "{{ user.name }}"

- name: install downgrade script for downgrading packages
  aur:
    name: downgrade
  become_user: "{{ user.name }}"
