hostname: localhost
timezone: America/Los_Angeles
country: United States
locales:
  - en_US

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - modconf
  - block
  - sd-encrypt
  - filesystems
  - fsck

packages:
  - arch-wiki-lite
  - dialog
  - glances
  - lsof
  - moreutils
  - rsync
  - sysstat
  - wpa_supplicant
