---
- name: restart pulseaudio as user
  systemd:
    name: pulseaudio.service
    scope: user
    state: restarted
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"

- name: enable bluetooth
  systemd:
    name: bluetooth.service
    enabled: yes
    state: started

- name: enable cron
  service:
    name: cronie.service
    enabled: yes
    state: started

- name: enable sshd
  service:
    name: sshd.socket
    enabled: yes
    state: restarted

- name: enable cups
  service:
    name: org.cups.cupsd.service
    state: started

- name: enable gdm
  service:
    name: gdm
    enabled: yes

- name: enable waybar
  systemd:
    name: waybar
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

- name: enable swayidle
  systemd:
    name: swayidle
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

- name: enable albert
  systemd:
    name: albert
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"

- name: enable pcscd smart card daemon
  systemd:
    name: pcscd.service
    enabled: yes
    state: started
