hostname: gzp

host_extra_packages:
  - r8168
host_extra_aur_packages: []

drive:
  device: /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S21NNSAG845105P
  table: gpt
  partitions:

    - name: bios_grub
      start: 1MiB
      end: 512MiB
      flags: [bios_grub]
      encrypt: false

    - name: root
      start: 512MiB
      end: 30GiB
      filesystem: ext4
      mountpoint: /
      encrypt: true

    - name: var
      start: 30GiB
      end: 40GiB
      filesystem: ext4
      mountpoint: /var
      encrypt: true

    - name: home
      start: 40GiB
      end: 100%
      filesystem: ext4
      mountpoint: /home
      encrypt: true
