hostname: vbox

host_extra_packages:
  - nvidia-340xx-utils
  - virtualbox-guest-modules-arch
  - virtualbox-guest-utils

host_extra_aur_packages: []

# UEFI/GPT
drive:
  device: /dev/sda
  table: gpt
  partitions:

    - name: root
      start: 512MiB
      end: 10GiB
      filesystem: ext4
      mountpoint: /
      encrypt: true

    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot/efi
      encrypt: false

    - name: var
      start: 10GiB
      end: 15GiB
      filesystem: ext4
      mountpoint: /var
      encrypt: true

    - name: home
      start: 15GiB
      end: 100%
      filesystem: ext4
      mountpoint: /home
      encrypt: true
