hostname: xps

host_extra_packages: []

host_extra_aur_packages:
  - aic94xx-firmware  # RAID controller driver
  - wd719x-firmware  # Western Digital SCSI driver

drive:
  device: /dev/sda
  table: gpt
  partitions:

    - name: root
      start: 512MiB
      end: 30GiB
      filesystem: ext4
      mountpoint: /
      encrypt: true

    - name: efi
      start: 0%
      end: 512MiB
      flags: [boot]
      filesystem: vfat
      mountpoint: /boot/efi
      encrypt: false

    - name: var
      start: 30GiB
      end: 60GiB
      filesystem: ext4
      mountpoint: /var
      encrypt: true

    - name: home
      start: 40GiB
      end: 100%
      filesystem: ext4
      mountpoint: /home
      encrypt: true
