hostname: xps

host_extra_packages: []
host_extra_aur_packages: []

drive:
  device: /dev/nvme0n1
  table: gpt
  partitions:
    # NOTE: Partitions must be defined in order of mounting.
    - name: root
      filesystem: ext4
      start: 512MiB
      end: 100%
      encrypt: true
      mountpoint: /

    - name: boot
      filesystem: vfat
      start: 0%
      end: 512MiB
      encrypt: false
      flags: [boot]
      mountpoint: /boot
